/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCidRouteImport } from './routes/c.$cid'
import { Route as CCidIndexRouteImport } from './routes/c.$cid.index'
import { Route as CCidMovesRouteImport } from './routes/c.$cid.moves'
import { Route as CCidInternalsRouteImport } from './routes/c.$cid.internals'
import { Route as CCidHitboxesRouteImport } from './routes/c.$cid.hitboxes'
import { Route as CCidGraphRouteImport } from './routes/c.$cid.graph'
import { Route as CCidCellsRouteImport } from './routes/c.$cid.cells'
import { Route as CCidMovesSlotRouteImport } from './routes/c.$cid.moves_.$slot'
import { Route as CCidCellsIdxRouteImport } from './routes/c.$cid.cells_.$idx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCidRoute = CCidRouteImport.update({
  id: '/c/$cid',
  path: '/c/$cid',
  getParentRoute: () => rootRouteImport,
} as any)
const CCidIndexRoute = CCidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCidRoute,
} as any)
const CCidMovesRoute = CCidMovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => CCidRoute,
} as any)
const CCidInternalsRoute = CCidInternalsRouteImport.update({
  id: '/internals',
  path: '/internals',
  getParentRoute: () => CCidRoute,
} as any)
const CCidHitboxesRoute = CCidHitboxesRouteImport.update({
  id: '/hitboxes',
  path: '/hitboxes',
  getParentRoute: () => CCidRoute,
} as any)
const CCidGraphRoute = CCidGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => CCidRoute,
} as any)
const CCidCellsRoute = CCidCellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => CCidRoute,
} as any)
const CCidMovesSlotRoute = CCidMovesSlotRouteImport.update({
  id: '/moves_/$slot',
  path: '/moves/$slot',
  getParentRoute: () => CCidRoute,
} as any)
const CCidCellsIdxRoute = CCidCellsIdxRouteImport.update({
  id: '/cells_/$idx',
  path: '/cells/$idx',
  getParentRoute: () => CCidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$cid': typeof CCidRouteWithChildren
  '/c/$cid/cells': typeof CCidCellsRoute
  '/c/$cid/graph': typeof CCidGraphRoute
  '/c/$cid/hitboxes': typeof CCidHitboxesRoute
  '/c/$cid/internals': typeof CCidInternalsRoute
  '/c/$cid/moves': typeof CCidMovesRoute
  '/c/$cid/': typeof CCidIndexRoute
  '/c/$cid/cells/$idx': typeof CCidCellsIdxRoute
  '/c/$cid/moves/$slot': typeof CCidMovesSlotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$cid/cells': typeof CCidCellsRoute
  '/c/$cid/graph': typeof CCidGraphRoute
  '/c/$cid/hitboxes': typeof CCidHitboxesRoute
  '/c/$cid/internals': typeof CCidInternalsRoute
  '/c/$cid/moves': typeof CCidMovesRoute
  '/c/$cid': typeof CCidIndexRoute
  '/c/$cid/cells/$idx': typeof CCidCellsIdxRoute
  '/c/$cid/moves/$slot': typeof CCidMovesSlotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$cid': typeof CCidRouteWithChildren
  '/c/$cid/cells': typeof CCidCellsRoute
  '/c/$cid/graph': typeof CCidGraphRoute
  '/c/$cid/hitboxes': typeof CCidHitboxesRoute
  '/c/$cid/internals': typeof CCidInternalsRoute
  '/c/$cid/moves': typeof CCidMovesRoute
  '/c/$cid/': typeof CCidIndexRoute
  '/c/$cid/cells_/$idx': typeof CCidCellsIdxRoute
  '/c/$cid/moves_/$slot': typeof CCidMovesSlotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/c/$cid'
    | '/c/$cid/cells'
    | '/c/$cid/graph'
    | '/c/$cid/hitboxes'
    | '/c/$cid/internals'
    | '/c/$cid/moves'
    | '/c/$cid/'
    | '/c/$cid/cells/$idx'
    | '/c/$cid/moves/$slot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/c/$cid/cells'
    | '/c/$cid/graph'
    | '/c/$cid/hitboxes'
    | '/c/$cid/internals'
    | '/c/$cid/moves'
    | '/c/$cid'
    | '/c/$cid/cells/$idx'
    | '/c/$cid/moves/$slot'
  id:
    | '__root__'
    | '/'
    | '/c/$cid'
    | '/c/$cid/cells'
    | '/c/$cid/graph'
    | '/c/$cid/hitboxes'
    | '/c/$cid/internals'
    | '/c/$cid/moves'
    | '/c/$cid/'
    | '/c/$cid/cells_/$idx'
    | '/c/$cid/moves_/$slot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CCidRoute: typeof CCidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$cid': {
      id: '/c/$cid'
      path: '/c/$cid'
      fullPath: '/c/$cid'
      preLoaderRoute: typeof CCidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$cid/': {
      id: '/c/$cid/'
      path: '/'
      fullPath: '/c/$cid/'
      preLoaderRoute: typeof CCidIndexRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/moves': {
      id: '/c/$cid/moves'
      path: '/moves'
      fullPath: '/c/$cid/moves'
      preLoaderRoute: typeof CCidMovesRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/internals': {
      id: '/c/$cid/internals'
      path: '/internals'
      fullPath: '/c/$cid/internals'
      preLoaderRoute: typeof CCidInternalsRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/hitboxes': {
      id: '/c/$cid/hitboxes'
      path: '/hitboxes'
      fullPath: '/c/$cid/hitboxes'
      preLoaderRoute: typeof CCidHitboxesRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/graph': {
      id: '/c/$cid/graph'
      path: '/graph'
      fullPath: '/c/$cid/graph'
      preLoaderRoute: typeof CCidGraphRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/cells': {
      id: '/c/$cid/cells'
      path: '/cells'
      fullPath: '/c/$cid/cells'
      preLoaderRoute: typeof CCidCellsRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/moves_/$slot': {
      id: '/c/$cid/moves_/$slot'
      path: '/moves/$slot'
      fullPath: '/c/$cid/moves/$slot'
      preLoaderRoute: typeof CCidMovesSlotRouteImport
      parentRoute: typeof CCidRoute
    }
    '/c/$cid/cells_/$idx': {
      id: '/c/$cid/cells_/$idx'
      path: '/cells/$idx'
      fullPath: '/c/$cid/cells/$idx'
      preLoaderRoute: typeof CCidCellsIdxRouteImport
      parentRoute: typeof CCidRoute
    }
  }
}

interface CCidRouteChildren {
  CCidCellsRoute: typeof CCidCellsRoute
  CCidGraphRoute: typeof CCidGraphRoute
  CCidHitboxesRoute: typeof CCidHitboxesRoute
  CCidInternalsRoute: typeof CCidInternalsRoute
  CCidMovesRoute: typeof CCidMovesRoute
  CCidIndexRoute: typeof CCidIndexRoute
  CCidCellsIdxRoute: typeof CCidCellsIdxRoute
  CCidMovesSlotRoute: typeof CCidMovesSlotRoute
}

const CCidRouteChildren: CCidRouteChildren = {
  CCidCellsRoute: CCidCellsRoute,
  CCidGraphRoute: CCidGraphRoute,
  CCidHitboxesRoute: CCidHitboxesRoute,
  CCidInternalsRoute: CCidInternalsRoute,
  CCidMovesRoute: CCidMovesRoute,
  CCidIndexRoute: CCidIndexRoute,
  CCidCellsIdxRoute: CCidCellsIdxRoute,
  CCidMovesSlotRoute: CCidMovesSlotRoute,
}

const CCidRouteWithChildren = CCidRoute._addFileChildren(CCidRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CCidRoute: CCidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
