#include "SCS_Node.h"

USCS_Node::USCS_Node() {
    this->ComponentClass = NULL;
    this->ComponentTemplate = NULL;
    this->bIsParentComponentNative = false;
    this->bIsFalseRoot = false;
    this->bIsNative = false;
    this->bVariableNameAutoGenerated = false;
}


