#!/usr/bin/env python3
"""Queue-oriented helper for Ghidra MCP documentation passes.

This intentionally keeps semantic decisions outside the script. It discovers
and snapshots work, then applies explicit JSON plans generated by an analyst or
LLM agent.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DEFAULT_BASE_URL = "http://127.0.0.1:8089"
DEFAULT_PROGRAM = "SoulcaliburVI.exe"
DEFAULT_OUT_DIR = Path("docs/investigations/ghidra-autolabel")

DENIED_TOOLS = {
    "/detect_malware_behaviors",
    "/find_anti_analysis_techniques",
    "/extract_iocs_with_context",
}


@dataclass
class McpClient:
    base_url: str
    program: str

    def _url(self, path: str, query: dict[str, Any] | None = None) -> str:
        if path in DENIED_TOOLS:
            raise RuntimeError(f"Denied by project policy: {path}")
        query = dict(query or {})
        query.setdefault("program", self.program)
        encoded = urllib.parse.urlencode(query, doseq=True)
        return f"{self.base_url}{path}" + (f"?{encoded}" if encoded else "")

    def get(self, path: str, **query: Any) -> Any:
        return self._request("GET", self._url(path, query))

    def post(self, path: str, body: dict[str, Any], **query: Any) -> Any:
        data = json.dumps(body).encode("utf-8")
        return self._request("POST", self._url(path, query), data)

    @staticmethod
    def _request(method: str, url: str, data: bytes | None = None) -> Any:
        req = urllib.request.Request(url, data=data, method=method)
        if data is not None:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                text = resp.read().decode("utf-8", errors="replace")
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"{method} {url} failed: {exc.code} {detail}") from exc
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            return text


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def ensure_out(out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir


def append_jsonl(path: Path, item: dict[str, Any]) -> None:
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(item, sort_keys=True) + "\n")


def parse_function_line(line: str) -> tuple[str, str] | None:
    # Examples:
    # "Name @ 1403e8840"
    # "Function: Name at 1403e8840"
    if " @ " in line:
        name, addr = line.rsplit(" @ ", 1)
        return name.strip(), "0x" + addr.strip().removeprefix("0x")
    if line.startswith("Function: ") and " at " in line:
        name, addr = line[len("Function: ") :].split(" at ", 1)
        return name.strip(), "0x" + addr.splitlines()[0].strip().removeprefix("0x")
    return None


def command_schema(client: McpClient, _args: argparse.Namespace) -> int:
    schema = client.get("/mcp/schema")
    tools = schema.get("tools", [])
    allowed = [t for t in tools if t.get("path") not in DENIED_TOOLS]
    print(json.dumps({"count": len(allowed), "denied": sorted(DENIED_TOOLS)}, indent=2))
    return 0


def command_scan(client: McpClient, args: argparse.Namespace) -> int:
    out_dir = ensure_out(args.out_dir)
    queue_path = out_dir / "queue.jsonl"
    seen: set[str] = set()
    patterns = args.pattern or ["FUN_", "Replay", "LuxBattle"]

    for pattern in patterns:
        result = client.get("/search_functions", name_pattern=pattern, limit=args.limit)
        lines = result if isinstance(result, list) else str(result).splitlines()
        for line in lines:
            parsed = parse_function_line(str(line))
            if not parsed:
                continue
            name, address = parsed
            if address in seen:
                continue
            seen.add(address)
            append_jsonl(
                queue_path,
                {
                    "status": "queued",
                    "reason": f"name pattern {pattern!r}",
                    "name": name,
                    "address": address,
                    "program": client.program,
                    "created_at": now_iso(),
                },
            )

    print(f"queued {len(seen)} candidates in {queue_path}")
    return 0


def read_queue(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    items: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    return items


def command_claim(_client: McpClient, args: argparse.Namespace) -> int:
    queue_path = args.out_dir / "queue.jsonl"
    items = read_queue(queue_path)
    completed = {i.get("address") for i in items if i.get("status") == "completed"}
    claimed = {i.get("address") for i in items if i.get("status") == "claimed"}

    for item in items:
        if item.get("status") != "queued":
            continue
        address = item.get("address")
        if address in completed or address in claimed:
            continue
        claim = dict(item)
        claim["status"] = "claimed"
        claim["claimed_at"] = now_iso()
        append_jsonl(queue_path, claim)
        print(json.dumps(claim, indent=2))
        return 0

    print("no queued candidates")
    return 1


def command_snapshot(client: McpClient, args: argparse.Namespace) -> int:
    out_dir = ensure_out(args.out_dir)
    address = normalize_address(args.address)
    fn_info = client.get("/get_function_by_address", address=address)
    name = extract_function_name(fn_info) or address
    slug = safe_slug(f"{address}_{name}")

    snapshot = {
        "created_at": now_iso(),
        "program": client.program,
        "address": address,
        "function_info": fn_info,
        "decompile": client.get("/decompile_function", address=address),
        "disassembly": client.get("/disassemble_function", address=address),
        "variables": client.get("/get_function_variables", function_name=name),
        "plate": client.get("/get_plate_comment", address=address),
        "xrefs": safe_get(client, "/get_function_xrefs", name=name),
        "completeness": client.get("/analyze_function_completeness", function_address=address, compact="true"),
    }

    path = out_dir / f"{slug}.snapshot.json"
    path.write_text(json.dumps(snapshot, indent=2, sort_keys=True), encoding="utf-8")
    print(path)
    return 0


def safe_get(client: McpClient, path: str, **query: Any) -> Any:
    try:
        return client.get(path, **query)
    except Exception as exc:  # keep snapshots useful even when one analyzer fails
        return {"error": str(exc)}


def normalize_address(address: str) -> str:
    text = address.strip()
    return text if text.startswith("0x") else f"0x{text}"


def extract_function_name(info: Any) -> str | None:
    if isinstance(info, dict):
        text = info.get("result") or info.get("function_name") or ""
    else:
        text = str(info)
    parsed = parse_function_line(text)
    return parsed[0] if parsed else None


def safe_slug(text: str) -> str:
    keep = []
    for ch in text:
        keep.append(ch if ch.isalnum() or ch in "._-" else "_")
    return "".join(keep).strip("_")[:180]


def command_apply_plan(client: McpClient, args: argparse.Namespace) -> int:
    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    program = plan.get("program", client.program)
    if program != client.program:
        client = McpClient(client.base_url, program)
    address = normalize_address(required(plan, "address"))

    print(f"{'APPLY' if args.apply else 'DRY-RUN'} {address} in {client.program}")
    validate_plan_shape(plan)

    if not args.apply:
        print(json.dumps(summarize_plan(plan), indent=2))
        return 0

    for struct in plan.get("structs", []):
        create_struct_if_missing(client, struct)

    if plan.get("function_name"):
        client.post(
            "/rename_function_by_address",
            {"function_address": address, "new_name": plan["function_name"]},
        )

    if plan.get("prototype"):
        client.post(
            "/set_function_prototype",
            {
                "function_address": address,
                "prototype": plan["prototype"],
                "calling_convention": plan.get("calling_convention", ""),
            },
        )

    variables = plan.get("variables", {})
    if variables:
        client.post(
            "/set_variables",
            {
                "function_address": address,
                "variables": json.dumps(variables),
                "program": client.program,
            },
        )

    comments = plan.get("comments", {})
    if comments:
        client.post(
            "/batch_set_comments",
            {
                "address": address,
                "plate_comment": comments.get("plate", ""),
                "decompiler_comments": comments.get("decompiler", []),
                "disassembly_comments": comments.get("disassembly", []),
            },
        )

    score = client.get("/analyze_function_completeness", function_address=address, compact="true")
    print(json.dumps({"completeness": score}, indent=2))
    if args.save:
        print(client.get("/save_program"))
    return 0


def create_struct_if_missing(client: McpClient, struct: dict[str, Any]) -> None:
    name = required(struct, "name")
    existing = client.get("/validate_data_type_exists", type_name=name)
    if isinstance(existing, str) and "does not exist" not in existing.lower():
        return
    if isinstance(existing, dict) and existing.get("exists"):
        return

    root_name = data_type_base_name(name)
    if root_name != name and not struct.get("allow_duplicate_type_name"):
        root_existing = client.get("/validate_data_type_exists", type_name=root_name)
        if isinstance(root_existing, str) and "does not exist" not in root_existing.lower():
            raise ValueError(
                f"refusing to create namespaced duplicate {name!r}; "
                f"canonical root type {root_name!r} already exists"
            )
        if isinstance(root_existing, dict) and root_existing.get("exists"):
            raise ValueError(
                f"refusing to create namespaced duplicate {name!r}; "
                f"canonical root type {root_name!r} already exists"
            )

    client.post("/create_struct", {"name": name, "fields": struct.get("fields", [])})


def data_type_base_name(name: str) -> str:
    return name.replace("\\", "/").rstrip("/").rsplit("/", 1)[-1]


def required(obj: dict[str, Any], key: str) -> str:
    value = obj.get(key)
    if not value:
        raise ValueError(f"missing required key: {key}")
    return str(value)


def validate_plan_shape(plan: dict[str, Any]) -> None:
    required(plan, "address")
    for forbidden in ("detect_malware_behaviors", "find_anti_analysis_techniques", "extract_iocs_with_context"):
        if forbidden in json.dumps(plan):
            raise ValueError(f"plan contains denied tool name: {forbidden}")
    comments = plan.get("comments", {})
    if comments and "plate" not in comments:
        raise ValueError("comments object must include a plate key; use empty string only to clear intentionally")


def summarize_plan(plan: dict[str, Any]) -> dict[str, Any]:
    return {
        "address": plan.get("address"),
        "function_name": plan.get("function_name"),
        "prototype": plan.get("prototype"),
        "struct_count": len(plan.get("structs", [])),
        "variable_count": len(plan.get("variables", {})),
        "has_comments": bool(plan.get("comments")),
    }


def command_loop(client: McpClient, args: argparse.Namespace) -> int:
    ensure_out(args.out_dir)
    if not args.pattern:
        args.pattern = ["FUN_", "Replay", "LuxBattle"]
    while True:
        command_scan(client, args)
        items = read_queue(args.out_dir / "queue.jsonl")
        queued = [i for i in items if i.get("status") == "queued"]
        if queued:
            address = queued[-1]["address"]
            snapshot_args = argparse.Namespace(address=address, out_dir=args.out_dir)
            command_snapshot(client, snapshot_args)
        time.sleep(args.sleep)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--program", default=DEFAULT_PROGRAM)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("schema")

    scan = sub.add_parser("scan")
    scan.add_argument("--limit", type=int, default=100)
    scan.add_argument("--pattern", action="append")

    sub.add_parser("claim")

    snapshot = sub.add_parser("snapshot")
    snapshot.add_argument("address")

    apply_plan = sub.add_parser("apply-plan")
    apply_plan.add_argument("plan", type=Path)
    apply_plan.add_argument("--apply", action="store_true")
    apply_plan.add_argument("--save", action="store_true")

    loop = sub.add_parser("loop")
    loop.add_argument("--limit", type=int, default=100)
    loop.add_argument("--pattern", action="append")
    loop.add_argument("--sleep", type=int, default=30)
    return parser


def main(argv: list[str]) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    client = McpClient(args.base_url, args.program)
    commands = {
        "schema": command_schema,
        "scan": command_scan,
        "claim": command_claim,
        "snapshot": command_snapshot,
        "apply-plan": command_apply_plan,
        "loop": command_loop,
    }
    return commands[args.cmd](client, args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
